### ISSUE TITLE
Image generator doesn't work with multi-agents

### ISSUE THREAD

**Issue by marcusschiesser** [ragapp/ragapp#189]
Tested with gpt4-mini, this query `Write an article about the flooding in central europe` and this agents YAML:
```
35bc3bd3-7af8-4f16-8079-1a3114d1d41d:
  created_at: 2024-09-17 05:18:26.367614
  name: Analyst
  role: Expert in analyzing news material
  system_prompt: 'You are an expert in analyzing news material, especially economic,
    political, and financial questions. Don''t make up any facts; use the provided
    material. '
  tools:
    DuckDuckGo:
      config: {}
      custom_prompt: ''
      enabled: false
    ImageGenerator:
      config:
        api_key: ''
      custom_prompt: ''
      enabled: false
    Interpreter:
      config:
        api_key: ''
      custom_prompt: ''
      enabled: false
    OpenAPI:
      config:
        openapi_uri: null
      custom_prompt: ''
      enabled: false
    QueryEngine:
      config: {}
      custom_prompt: ''
      enabled: false
    Wikipedia:
      config: {}
      custom_prompt: ''
      enabled: false
8d53880d-906d-404c-b5f4-91fb07567b85:
  created_at: 2024-09-16 02:53:57.746566
  name: Researcher
  role: Expert in researching news material
  system_prompt: You are an expert in researching material for news-related questions.
    Don't make up any information; instead, use your tools to gather the information.
  tools:
    DuckDuckGo:
      config: {}
      custom_prompt: ''
      enabled: true
    ImageGenerator:
      config:
        api_key: ''
      custom_prompt: ''
      enabled: false
    Interpreter:
      config:
        api_key: ''
      custom_prompt: ''
      enabled: false
    OpenAPI:
      config:
        openapi_uri: null
      custom_prompt: ''
      enabled: false
    QueryEngine:
      config: {}
      custom_prompt: ''
      enabled: false
    Wikipedia:
      config: {}
      custom_prompt: ''
      enabled: true
e8e9c738-1abf-4f8c-833e-65e2e786e2b8:
  created_at: 2024-09-17 05:19:27.390006
  name: Reporter
  role: Summarizes given information to present it to an audience
  system_prompt: You are an expert in presenting complex questions to a broad audience.
    Your job requires that you receive thoroughly researched material beforehand.
    Don't make up any facts; use the provided material. Also, generate an image for
    your article.
  tools:
    DuckDuckGo:
      config: {}
      custom_prompt: ''
      enabled: false
    ImageGenerator:
      config:
        api_key: xxxxx
      custom_prompt: ''
      enabled: true
    Interpreter:
      config:
        api_key: ''
      custom_prompt: ''
      enabled: false
    OpenAPI:
      config:
        openapi_uri: null
      custom_prompt: ''
      enabled: false
    QueryEngine:
      config: {}
      custom_prompt: ''
      enabled: false
    Wikipedia:
      config: {}
      custom_prompt: ''
      enabled: false
```
